import "./globals.css";
import ReduxProvider from "./redux/redux-provider";

export const metadata = {
    title: "Trends Scope",
    description: "Generated by create next app",
};

const inter = {
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    variable: "--font-inter",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.variable}>{children}</body>
        </html>
    );
}
